// import type { Metadata } from "next";
// import { Poppins } from "next/font/google";
// import "./globals.css";
// import Sidebar from "@/components/Sidebar";
// import Navbar from "@/components/Navbar";
// import { TooltipProvider } from "@/components/ui/tooltip";
// import { headers } from "next/headers";

// const poppins = Poppins({
//   subsets: ["latin"],
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
//   variable: "--font-poppins",
// });

// export const metadata: Metadata = {
//   title: "My App",
//   description: "Generated by Next.js",
// };

// export default async function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   const pathname = (await headers()).get("x-pathname") || "";

//   const isAuthPage = pathname === "/login";

//   return (
//     <html lang="en">
//       <body className={poppins.className}>
//         {isAuthPage ? (
//           children
//         ) : (
//           <div className="flex h-screen overflow-hidden bg-[#f8fafc]">
//             <Sidebar />

//             <div className="flex-1 flex flex-col min-w-0 overflow-hidden">
//               <Navbar />
//               <main className="flex-1 overflow-y-auto p-4 md:p-8">
//                 {children}
//               </main>
//             </div>
//           </div>
//         )}
//       </body>
//     </html>
//   );
// }


// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "HR Management",
  description: "HR Management System",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}
        <Toaster />
      </body>
    </html>
  );
}